cameras:
  camera_1:
    fps: 0
    name: PREVIEW Ch1
    prediction_area:
      color: [0, 255, 0]
      enabled: true
    prediction_border:
      color: [255, 0, 0]
      enabled: true
    resolution: [1280, 720]
    source: d:/1-kerja-2025/uniform-detection/src/video/test.mp4
  camera_2:
    fps: 0
    name: PREVIEW CH2
    prediction_area:
      color: [0, 255, 0]
      enabled: true
    prediction_border:
      color: [255, 0, 0]
      enabled: true
    resolution: [1280, 720]
    source: d:/1-kerja-2025/uniform-detection/src/video/test-2.mp4
config_path: d:/1-kerja-2025/uniform-detection/config/config.yaml
coordinates:
  '0':
    border:
    - [420, 112]
    - [217, 180]
    - [212, 355]
    - [428, 420]
    - [634, 339]
    - [620, 140]
    - [418, 110]
    area_pred:
    - [315, 152]
    - [499, 392]
  '1':
    border:
    - [352, 117]
    - [405, 178]
    - [599, 149]
    - [653, 485]
    - [347, 558]
    - [175, 198]
    - [350, 114]
    - [349, 112]
    area_pred:
    - [350, 115]
    - [429, 532]
